apiVersion: v2
name: cluster-api-provider-kubevirt
description: A Helm chart for Cluster API Provider KubeVirt
type: application
version: 1.6.0
appVersion: "0.1.10"
annotations:
  cluster.x-k8s.io/provider: infrastructure-kubevirt
  cluster.x-k8s.io/v1beta1: v1beta1
