apiVersion: v2
name: cluster-api-provider-hosted-control-plane
description: A Helm chart for Cluster API Provider Hosted Control Plane
type: application
version: 1.0.0
appVersion: "1.5.0"
annotations:
  cluster.x-k8s.io/provider: control-plane-hosted-control-plane
  cluster.x-k8s.io/v1beta1: v1alpha1
dependencies:
  - name: gateway-helm
    version: "v1.4.0"
    repository: "oci://docker.io/envoyproxy"
    condition: envoyGateway.enabled
