{{- if .Values.gateway.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.gatewayClass.name }}
spec:
  controllerName: {{ .Values.gateway.gatewayClass.controllerName }}
  {{- if .Values.gateway.envoyProxy.create }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ include "tinkerbell-hcp-kubeadm.clusterName" . }}-proxy-config
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
