apiVersion: v2
name: cilium-cni
description: A KCM service chart for Cilium CNI deployment on workload clusters
type: application
version: 1.0.0
appVersion: "1.18.5"
annotations:
  k0rdent.mirantis.com/type: service
dependencies:
  - name: cilium
    version: "1.18.5"
    repository: "https://helm.cilium.io/"
