apiVersion: v2
name: kubevirt
description: A Helm chart for KubeVirt - Kubernetes Virtualization API and runtime
type: application
version: 1.6.2
appVersion: "1.6.2"
keywords:
  - kubevirt
  - virtualization
  - kubernetes
home: https://kubevirt.io/
sources:
  - https://github.com/kubevirt/kubevirt
