apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlaneEndpoint.host | quote }}
    port: {{ .Values.controlPlaneEndpoint.port }}
