apiVersion: v2
name: cluster-api-provider-tinkerbell
description: A Helm chart for Cluster API Provider Tinkerbell
type: application
version: 1.1.0
appVersion: "0.6.8"
annotations:
  cluster.x-k8s.io/provider: infrastructure-tinkerbell
  cluster.x-k8s.io/v1beta1: v1beta1
dependencies:
  - name: tinkerbell
    version: "v0.22.0"
    repository: "oci://ghcr.io/tinkerbell/charts"
    condition: tinkerbell.enabled
  - name: kube-vip-cloud-provider
    version: "0.2.9"
    repository: "https://kube-vip.github.io/helm-charts"
    condition: kubeVipCloudProvider.enabled
